### ISSUE TITLE
deal with moving `plot_match_success_rate()` into `r2dii.plot` TODO

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#236]
- related to #213 

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/03d3c10346d3c0a0bb132cb225a3cce01bfb307b/R/plots.R#L1-L2

@MonikaFu is there still any realistic plan to move `plot_match_success_rate()` into `r2dii.plot`?

**Comment by jdhoffa** [comment]
Either way, suggested actions here:

- [x] Open an issue in `r2dii.plot` with the suggestion
- [x] Remove the `TODO` from `pacta.multi.loanbook@main`
- [x] Close this issue

**Comment by cjyetman** [comment]
now tracked in https://github.com/RMI-PACTA/r2dii.plot/issues/574

**Comment by MonikaFu** [comment]
@cjyetman I have no visibility on this. Depending on how useful that would be we could do this. Decision up to @jdhoffa and @jacobvjk I would say.

**Comment by cjyetman** [comment]
> @cjyetman I have no visibility on this. Depending on how useful that would be we could do this. Decision up to @jdhoffa and @jacobvjk I would say.

@MonikaFu I have already removed the TODO comment from the code in this repo, and this issue will be closed when that PR merges.

The idea of moving `plot_match_success_rate()` into `r2dii.plot` has already been moved to https://github.com/RMI-PACTA/r2dii.plot/issues/574, so it is now completely in your hands as the maintainer of that repo 😁

**Comment by jdhoffa** [comment]
> @cjyetman I have no visibility on this. Depending on how useful that would be we could do this. Decision up to @jdhoffa and @jacobvjk I would say.

My recommendation is to leave https://github.com/RMI-PACTA/r2dii.plot/issues/574 open without action. That way the idea is tracked (in a better format than a `TODO`), but we don't need to action anything yet (which I see no reason to do in the short term)

**Comment by cjyetman** [comment]
> > @cjyetman I have no visibility on this. Depending on how useful that would be we could do this. Decision up to @jdhoffa and @jacobvjk I would say.
> 
> My recommendation is to leave [RMI-PACTA/r2dii.plot#574](https://github.com/RMI-PACTA/r2dii.plot/issues/574) open without action. That way the idea is tracked (in a better format than a `TODO`), but we don't need to action anything yet (which I see no reason to do in the short term)

https://github.com/RMI-PACTA/r2dii.plot/issues/574 appears to have been a duplicate of https://github.com/RMI-PACTA/r2dii.plot/issues/563 🤣 so I closed it (with appropriate comment and link) and left the original open

so just to be clear, this concept has now been moved to https://github.com/RMI-PACTA/r2dii.plot/issues/563

**Comment by jacobvjk** [comment]
I think there is an argument for making the match success rate available in r2dii.plot so that it can be used in individual analyses in low threshold way. I am thinking IFC applications for example. It would also be good to have something like that available if/when we set up a P4B cookbook. But definitely no urgency right now

**Comment by cjyetman** [comment]
> I think there is an argument for making the match success rate available in r2dii.plot so that it can be used in individual analyses in low threshold way. I am thinking IFC applications for example. It would also be good to have something like that available if/when we set up a P4B cookbook. But definitely no urgency right now

@jacobvjk maybe add that here https://github.com/RMI-PACTA/r2dii.plot/issues/563
